<a href="https://colab.research.google.com/github/Ctanicla8/sf_data_science/blob/main/ModNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
nd_array = np.linspace(0, 6, 12, endpoint=False).reshape(3, 4)
nd_array[2:4]
nd_array[:2, 2]

array([1., 3.])

In [ ]:
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

In [ ]:
elem_5_3 = mystery[4, 2]
print(elem_5_3)

30305


In [ ]:
mystery.shape

(6, 7)

In [ ]:
last = mystery[5, 6]
print(last)

-32037


In [ ]:
line = mystery[3:4]
line_4 = line[0]
print(line_4)

[13240  7994 32592 20149 13754 11795  -564]


In [ ]:
col = mystery[0:, 5:6]
col_1 = col.transpose()
col_2 = col_1[0]
print(col_2)

[-17182  15790  25397  11795  12578    -47]


In [ ]:
part = mystery[1:4, 2:5]
print(part)

[[-1297 -4593  6451]
 [28655 -6012 21762]
 [32592 20149 13754]]


In [ ]:
r = mystery[0:, 6:7]
r = r[::-1]
re = r.transpose()
rev = re[0]
print(rev)

[-32037  29943   -564   8225   7181 -18049]


In [ ]:
trans = mystery.transpose()
print(trans)

[[-13586  25936  13348  13240 -21725 -16841]
 [ 15203 -30968  28049   7994  -8681 -25392]
 [ 28445  -1297  28655  32592  30305 -17278]
 [-27117  -4593  -6012  20149  22260  11740]
 [ -1781   6451  21762  13754 -17918   5916]
 [-17182  15790  25397  11795  12578    -47]
 [-18049   7181   8225   -564  29943 -32037]]


In [3]:
arr = np.array([23,12,45,12,23,4,15,3])

In [4]:
arr_new = np.sort(arr)
print(arr)
print(arr_new)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [5]:
print(arr.sort())

None


In [6]:
print(arr)

[ 3  4 12 12 15 23 23 45]


In [7]:
data = np.array([4, 9, -4, 3])

In [8]:
roots = np.sqrt(data)
roots

<ipython-input-8-415e7f928f58>:1: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])