In [1]:
import numpy as np
from collections import Counter

In [2]:
nd_array = np.linspace(0, 6, 12, endpoint=False).reshape(3, 4)
nd_array[2:4]
nd_array[:2, 2]
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [ ]:
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

In [ ]:
elem_5_3 = mystery[4, 2]
print(elem_5_3)

30305


In [ ]:
mystery.shape

(6, 7)

In [ ]:
last = mystery[5, 6]
print(last)

-32037


In [ ]:
line = mystery[3:4]
line_4 = line[0]
print(line_4)

[13240  7994 32592 20149 13754 11795  -564]


In [ ]:
col = mystery[0:, 5:6]
col_1 = col.transpose()
col_2 = col_1[0]
print(col_2)

[-17182  15790  25397  11795  12578    -47]


In [ ]:
part = mystery[1:4, 2:5]
print(part)

[[-1297 -4593  6451]
 [28655 -6012 21762]
 [32592 20149 13754]]


In [ ]:
r = mystery[0:, 6:7]
r = r[::-1]
re = r.transpose()
rev = re[0]
print(rev)

[-32037  29943   -564   8225   7181 -18049]


In [ ]:
trans = mystery.transpose()
print(trans)

[[-13586  25936  13348  13240 -21725 -16841]
 [ 15203 -30968  28049   7994  -8681 -25392]
 [ 28445  -1297  28655  32592  30305 -17278]
 [-27117  -4593  -6012  20149  22260  11740]
 [ -1781   6451  21762  13754 -17918   5916]
 [-17182  15790  25397  11795  12578    -47]
 [-18049   7181   8225   -564  29943 -32037]]


In [ ]:
arr = np.array([23,12,45,12,23,4,15,3])

In [ ]:
arr_new = np.sort(arr)
print(arr)
print(arr_new)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [ ]:
print(arr.sort())

None


In [ ]:
print(arr)

[ 3  4 12 12 15 23 23 45]


In [ ]:
data = np.array([4, 9, -4, 3])

In [ ]:
roots = np.sqrt(data)
np.isnan(roots)
roots[np.isnan(roots)] = 0
print(roots)
sum(roots)


[2.         3.         0.         1.73205081]


<ipython-input-12-40d602e56086>:1: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


6.732050807568877

Задание 7.4

In [ ]:
mystery1 = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)
nans_index = np.isnan(mystery1)
nans_index

array([False, False, False,  True, False, False, False, False,  True,
       False, False, False,  True, False, False])

In [ ]:
c = Counter(nans_index)
n_nan = c[True]
n_nan

3

In [ ]:
mystery_new = mystery1
mystery_new[np.isnan(mystery_new)] = 0

array([ 12279., -26024.,  28745.,      0.,  31244.,  -2365.,  -6974.,
        -9212.,      0., -17722.,  16132.,  25933.,      0., -16431.,
        29810.], dtype=float32)

In [ ]:
mystery_int = np.int32(mystery1)
array = np.sort(mystery1)
print(mystery_int)
print(array)

[ 12279 -26024  28745      0  31244  -2365  -6974  -9212      0 -17722
  16132  25933      0 -16431  29810]
[-26024. -17722. -16431.  -9212.  -6974.  -2365.      0.      0.      0.
  12279.  16132.  25933.  28745.  29810.  31244.]


In [ ]:
table = array.reshape((5, 3), order='F')
table

array([[-26024.,  -2365.,  16132.],
       [-17722.,      0.,  25933.],
       [-16431.,      0.,  28745.],
       [ -9212.,      0.,  29810.],
       [ -6974.,  12279.,  31244.]], dtype=float32)

In [ ]:
c = table[0:, 1:2]
co = c.transpose()
col = co[0]
print(col)

[-2365.     0.     0.     0. 12279.]


Векторы

In [ ]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

In [ ]:
vec1 + vec2
vec1 * vec2
vec1 > vec2

array([False, False,  True, False])

In [ ]:
vec = np.array([3, 4])

Vector length

In [ ]:
length = np.sqrt(np.sum(vec ** 2))
length = np.linalg.norm(vec)
length

5.0

In [ ]:
vec3 = np.array([0, 3, 5])
vec4 = np.array([12, 4, 7])

Distance between vectors

In [ ]:
distance = np.sqrt(np.sum((vec3 - vec4) ** 2))
distance

12.206555615733702

In [ ]:
distance = np.linalg.norm(vec3 - vec4)
distance

12.206555615733702

Scalar product of vectors

In [ ]:
vec5 = np.arange(1,6)
vec6 = np.linspace(10, 20, 5)

In [ ]:
scalar_product = np.sum(vec5 * vec6)
scalar_product

250.0

In [ ]:
scalar_product = np.dot(vec5, vec6)
scalar_product

250.0

Задания 8,4 - 8,6

In [ ]:
a = np.array([23, 34, 27])
b = np.array([-54, 1, 46])
c = np.array([46, 68, 54])

In [ ]:
length_a = np.linalg.norm(a)
length_b = np.linalg.norm(b)
length_c = np.linalg.norm(c)

8,4 Сонаправленность:

In [ ]:
print(length_a + length_b == np.linalg.norm(a+b))
print(length_a + length_c == np.linalg.norm(a+c))
print(length_c + length_b == np.linalg.norm(c+b))

False
True
False


8,5 Расстояние больше ста?

In [ ]:
print(np.linalg.norm(a-b))
print(np.linalg.norm(a-c))
print(np.linalg.norm(b-c))

85.901105930017
49.13247398615299
120.6358155772986


8,6 Перпендикулярность

In [ ]:
print(np.dot(a, b) == 0)
print(np.dot(a, c) == 0)
print(np.dot(c, b) == 0)

False
False
False


Минимум, максимум, среднее

In [ ]:
vec = np.array([2,7,18,28,18,1,8,4])
vec.min()

1

In [ ]:
np.max(vec)

28

In [ ]:
vec.mean()

10.75

In [ ]:
np.median(vec)

7.5

In [ ]:
np.std(vec)

8.954747344286158

SEED генератор

In [5]:
np.random.seed(22)
np.random.randint(10, size=(3,4))

array([[5, 4, 0, 4],
       [6, 6, 4, 8],
       [4, 2, 8, 7]])

In [8]:
np.random.seed(100)
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))

[8 8 3]
[7 7 0]
[4 2 5]
[2 2 2]


Задание 9.6 

In [ ]:
np.random.seed(2021)
simple = np.random.rand()
randoms = np.random.uniform(-150, 2021, size=120)
table = np.random.randint(1, 101, size=(3, 2))
even = np.arange(2, 17, 2)
mix = even
np.random.shuffle(mix)
select = np.random.choice(even, size=3, replace=False)
triplet = np.random.permutation(select)